name: Termcheckin

on:
  schedule:
    - cron: "5 16 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run 
        env:
          BIN_URL: ${{ secrets.BIN_URL }}
        run: |
          curl -L -o termcheckin.exe $env:BIN_URL
          ./termcheckin.exe

          Remove-Item -Path './termcheckin.exe' -Force
          
          # Read the current content of time.log
          $existingContent = Get-Content -Path 'time.log'

          # Add "success" to the content and write it to temp file
          "success" | Add-Content -Path 'temp.log'
          
          # Append the existing content to temp.log
          $existingContent | Add-Content -Path 'temp.log'
          
          # Move the temp.log to overwrite time.log
          Move-Item -Path 'temp.log' -Destination 'time.log' -Force
          
      - name: Commit
        run: |
          git config --global user.email D0OR@pm.me
          git config --global user.name D0O0R
          git add .
          git commit -m "learn" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
